### PR TITLE
add PostgreSQL driver

### PR DESCRIPTION
**Pull request by nitram509**
add PostgreSQL driver as a dependency, so it will be bundled into Docker image...
as proposed in #254

### CODE REVIEW

**Comment by saig0** [comment]
@nitram509 thank you for your contribution 🎉 I'll review your PR soon 👀

**Comment by danshapir** [comment]
@saig0 can you please release 2.1.1 (not just a snapshot)? 2.1.0 doesn't work with PSQL driver.

**Comment by saig0** [comment]
@danshapir yes :sweat_smile: I'll build a release in the next few days :building_construction:

**Comment by saig0** [comment]
@danshapir a new version [2.2.0](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.2.0) is released :tada:

**Comment by ojgutierrez** [comment]
Hi, can you please add Mysql Support, driver not found since 2.1.0 version
Thanks

**Comment by saig0** [comment]
> Hi, can you please add Mysql Support, driver not found since 2.1.0 version

There is no MySQL support until now. Please create a new issue for it. 
Feel free to contribute by submitting a PR similar to this one :rocket:

**Pull request merged**
