### PR TITLE
I can sort processes and process instances

### LINKED ISSUE #275: Sorting - everything is sorted ASC and not DESC
The normal flow of interacting with the monitor is to monitor the latest jobs, instances, workflows, and so on, but everything is ordered ASC and not DESC (and there isn't any sorting ability).

How can one have the tables sorted DESC and not ASC? If you could direct me to the code I don't mind doing a pull request (not a java developer, but...).

Thanks!

### PR DESCRIPTION
**Pull request by saig0**
* show the deployment time of processes
* add sorting of processes by deployment time
* add sorting of process instances by start time 

closes #275

### CODE REVIEW

**Comment by danshapir** [comment]
@saig0 is the sorting done on the client side? I dont see any backend logic here.

**Comment by saig0** [comment]
@danshapir no, the sorting happens in the backend :smile:

It is a built-in feature of [Spring data web](https://www.baeldung.com/spring-data-web-support#the-sorthandlermethodargumentresolver-class). Every repository supports pagination and sorting by default. So, the client just need to add the sorting parameter :rocket: 

I build the sorting in a way that is easy to adapt for other tables. See here:

https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/293/files#diff-dc86492ab8732f0eeedb88ff1c1074e9024959f535dc8cda0dcf2c3d0607626d

**Comment by danshapir** [comment]
Awesome!

**Comment by danshapir** [comment]
@saig0 can you release a new docker version?

**Comment by saig0** [comment]
@danshapir there is also a Docker image. You can get it here: 

```
docker pull ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.1.0
```

**Pull request merged**
