### PR TITLE
feat(UI): add pagination for detail views in process instance improves rendering time for large workflows

### PR DESCRIPTION
**Pull request by nitram509**
Motivation:
While using this Simple Monitor for some performance tests, I realized that instances with 300+ events
(let it be timers, jobs, incidents etc.) lead to trouble loading the DOM in the browsers. The reason for that is simple:
the process instance view did server-side rendering all information as HTML tables. This led to 5MB+ large HTML files,
which took ca. 10s to load the DOM in Chrome, on my MacBook Pro.
Some more extreme tests with 3000+ events also lead to server-side timeouts.

This PR tries to solve the performance issue by keeping the server-side rendering and introducing pagination
per individual detail view (timers, jobs, audit log, etc.)

This PR covers:
* refactoring: move all DTOs into their own package
* refactoring: split almighty ViewController into multiple ones, per each main view (see top navigation)
* refactoring: split InstanceViewController into multiple smaller ones, per each detail view
* refactoring: split process instance detail views into multiple pages in order to introduce pagination
* refactoring: re-formatted code, using google java code style, as stated in camunda-cloud/zeebe contribution guidelines

I left the individual commits in, in case someone likes to see the intermediate refactoring steps.

Resulting from the refactorings, the behavior in the UI is now slightly different.
Each subview in the process instance view is now a standalone page. This means not all details are loaded at once anymore,
but the *ViewController makes use of Spring's ```Pageable``` methodology.
The result is significantly faster page loading and rendering.

Here's how the UI looks now... (visually the same, except we have introduced new query parameter)
Screenshot 2022-01-25 at 09 43 31

Any feedback is welcome.

### CODE REVIEW

**Comment by nitram509** [comment]
@saig0 without putting any pressure, I just want to "ping" the PR is now considered ready.

**Comment by saig0** [comment]
@nitram509 awesome :tada: 
I'll review the PR as soon as I can. But currently, it is not so easy for me to find the time for my side projects :sob:

**Comment by nitram509** [comment]
Thank you @saig0 for your support 👍

**Review by saig0 — APPROVED** [review]
@nitram509 awesome :tada: 
This is a huge improvement :rocket: 

Personally, I would prefer more composition over inheritance but it works and we don't need to change it now. Thank you for this contribution :1st_place_medal:

**Pull request merged**
