### PR TITLE
Feature/error handler

### PR DESCRIPTION
**Pull request by jbiblio**
Please refer to https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/279. I'm creating a new PR, to circumvent an issue with cla-assistant. See comments over there.

In short, I'd like to improve the error handling by establishing a dedicated ExceptionHandler.

### CODE REVIEW

**Comment by jbiblio** [comment]
@saig0 As suggested in https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/279#issuecomment-894208956 here's the new PR, but I'm affraid it does not affect cla-assistant.

I've revoked it's OAuth-token and re-logged in, but it seems they remember me.

**Comment by saig0** [comment]
@celanthe can you help @jbiblio to solve the problem with the CLA bot? Thank you! :cookie:

**Comment by celanthe** [comment]
Hi @saig0 @jbiblio, as was already mentioned in #279, the CLA bot requires your commits to have the same email address as you specified on GitHub. If you could try [signing a CLA](https://cla-assistant.io/camunda-community-hub/) for the Camunda Community Hub GitHub Organization as a whole using the email address/name you specified on this GitHub account, and then re-running the CLA check for this PR, that would be great. 

If you run into any issues, I am happy to help!

**Comment by jbiblio** [comment]
Hi @celanthe,

grmbl. Thanks for your hint! I'm affraid I've needed some time to understand that I've mixed two accounts :-/

Since I hestitate to modify a branch that was published already I'll create a third PR.

I'm sorry for the hazzle! 
Best regards,
Michael

**Pull request closed without merging**
