### PR TITLE
feat(ui): incident view filtering by process id and time

### PR DESCRIPTION
**Pull request by nitram509**
implements #438 

### Demo/Screenshot
Screenshot 2022-10-05 at 16 45 13

### noteworthy changes

- introducing new dependencies for QueryDSL
   - reasoning QueryDSL is well supported with the Spring JPA framework and eases the filtering of various attributes
- there's a bug fix for popper.js, since the import was broken (visible in JS console of Chrome, when clicking a drop-down menu, created with bootstrap and then there was the error message, that popper.js was missing)
- on-top of the ticket, I do introduce sorting of error type and process id to further assist in finding incidents

### CODE REVIEW

**Comment by saig0** [comment]
@nitram509 thank you for your contribution. :tada:  I'll have a look at your PR in the next few days. :eyes:

**Comment by saig0** [comment]
@nitram509 I'll have a look at your PR next week.

**Review by saig0 — APPROVED** [review]
@nitram509 very cool. :tada: I like it. :+1:

**Comment by skayliu** [comment]
Hi, @nitram509 , did you forget to upload the `QIncidentEntity.java` ❓

**Pull request merged**
