### PR TITLE
feat: Bundle a MySQL driver

### PR DESCRIPTION
**Pull request by ian4h**
Add the mysql driver as a dependency.
As discusse in issue: https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/337
Based on previouse work to add the Postgres driver: https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/307

### CODE REVIEW

**Comment by saig0** [comment]
@ian4h thank you for your contribution. :tada:  I'll have a look at your PR in the next few days. :eyes:

**Comment by ian4h** [comment]
Hi @saig0 ok thanks no rush. 
Actually I've noticed an issue with the changes to use MYSQL so I'll ask for some feedback from you before making any changes. 
MYSQL defaults to a lower case table naming strategy. So when the repository goes to use a nativeQuery (for example in the ProcessRepository getElementInstanceStatisticsByKeyAndIntentIn() method) and is uses the upper case table names, then the query fails. 
The solution to this is add the following environment variable:
`- spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl`
I've tested this and it works as expected. 
I was going to just add some additional info to the README to document this solution for MYSQL databases. Is this ok with you or would you rather another solution?
Thanks

**Comment by saig0** [comment]
> I was going to just add some additional info to the README to document this solution for MYSQL databases. Is this ok with you or would you rather another solution?

Sounds fine to me. :+1: 

Thank you for coming up with the solution immediately.

**Comment by saig0** [comment]
@ian4h it would be nice to add a new profile for MySQL to the [docker-compose file](https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/main/docker/docker-compose.yml). It would make the testing a lot easier.

**Review by saig0 — APPROVED** [review]
@ian4h looks all good. Your PR is ready to merge. :tada:

**Pull request merged**
