### PR TITLE
feat: Support Redis Importer

### PR DESCRIPTION
**Pull request by VonDerBeck**
In order to make Zeebe Simple Monitor even more flexibel, I added the option to import events using Redis.
See https://github.com/camunda-community-hub/zeebe-redis-exporter.

The importer side is very similar to the Hazelcast Importer. So there is a lot reuse of the existing code. I moved the Protobuf specific importer classes to a package where they can be used by both, Hazelcast and Redis. The rest of the changes is simple setup and connection stuff.

Why Redis? Redis (https://redis.io/) offers a lot of options to us. We can use it as fast in-memory technology and simple transport layer. We can optionally add persistence, but it is not required. We have Redis streams at our hand which are great when we want to use multiple consumers and scaling on the event receiver side. If neither the Hazelcast nor the Kafka exporter fits the exact requirements, this could be the one.

If there are any questions and hints, let me know.

### CODE REVIEW

**Comment by michaelholtermann** [comment]
Hi @VonDerBeck, this sounds great!

We are using the Hazelcast integration. Because of the RingBuffer, this may lead to loosing events, which AFAICS is hard to detect and near to impossible to solve afterwards.

What do you say, would this issue go away with switching to Redis?

And do you know if it works well with high volumes from Zeebe, e.g. the monitor is still able to process incoming events?

Thanks in advance!

**Comment by VonDerBeck** [comment]
@nitram509,

looks like you have been in charge releasing the latest version of Zeebe Simple Monitor. On the other hand this repository is marked as "in search of a maintainer". Would you like to review my changes? Or should I simply merge it? Typically, when working on such a repo you have a strategy in mind where you like to see this thing in the future and PRs should fit into this long term vision. So your review would be very valuable for me. Just let me know 😃 

Thanks in advance
Gunnar

**Comment by nitram509** [comment]
> @nitram509,
> 
> looks like you have been in charge releasing the latest version of Zeebe Simple Monitor. On the other hand this repository is marked as "in search of a maintainer". Would you like to review my changes? Or should I simply merge it? Typically, when working on such a repo you have a strategy in mind where you like to see this thing in the future and PRs should fit into this long term vision. So your review would be very valuable for me. Just let me know 😃
> 
> Thanks in advance Gunnar

Hi Gunnar,
yes I'm glad to do the review ... just being a bit short of spare time ... likely will find some by the upcoming weekend.


Regards
Martin

**Comment by nitram509** [comment]
Thank you very much for this contribution @VonDerBeck  🚀

**Pull request merged**
